import Link from "next/link";
import { Package, ArrowLeft, CircleCheck } from "lucide-react";
import { db } from "@/lib/db";
import { sql } from "drizzle-orm";
import { Button } from "@/components/ui/button";

export const dynamic = "force-dynamic";
const statuses = ["pending", "payment_confirmed", "processing", "shipped", "in_transit", "delivered"];
export default async function ShipmentsPage() {
  const result = await db.execute(sql`SELECT id, recipient_name, city, state, country, payment_status, fulfillment_status, tracking_number, tracking_url, estimated_delivery, created_at FROM public.shipment_orders WHERE user_id = 'demo-user' ORDER BY created_at DESC`);
  const shipments = result.rows as Array<Record<string, string | null>>;
  return <main className="min-h-dvh bg-background"><header className="mx-auto flex max-w-4xl items-center gap-3 px-4 py-5"><Link href="/" className="text-muted-foreground"><ArrowLeft className="size-5" /></Link><div><p className="font-display text-lg">My shipments</p><p className="text-xs text-muted-foreground">Track every physical membership card</p></div></header><section className="mx-auto max-w-4xl space-y-5 px-4 pb-16"><h1 className="font-display text-3xl">Card delivery</h1>{shipments.length === 0 ? <div className="rounded-2xl border border-border bg-card p-8 text-center"><Package className="mx-auto size-8 text-primary" /><p className="mt-3 text-muted-foreground">No physical card orders yet.</p><Button asChild className="mt-5"><Link href="/create">Create a card</Link></Button></div> : shipments.map((shipment) => { const index = statuses.indexOf(String(shipment.fulfillment_status)); return <article key={shipment.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-medium">{shipment.recipient_name}</p><p className="text-sm text-muted-foreground">{shipment.city}{shipment.state ? `, ${shipment.state}` : ""} · {shipment.country}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs capitalize">{String(shipment.fulfillment_status).replaceAll("_", " ")}</span></div><div className="mt-6 grid grid-cols-6 gap-1">{statuses.map((status, i) => <div key={status} className="space-y-2 text-center"><div className={`mx-auto grid size-7 place-items-center rounded-full ${i <= index ? "bg-primary text-primary-foreground" : "bg-secondary text-muted-foreground"}`}>{i <= index ? <CircleCheck className="size-4" /> : i + 1}</div><p className="hidden text-[10px] capitalize text-muted-foreground sm:block">{status.replaceAll("_", " ")}</p></div>)}</div>{shipment.tracking_number && <p className="mt-5 text-sm">Tracking: {shipment.tracking_url ? <a className="text-primary underline" href={shipment.tracking_url} target="_blank" rel="noreferrer">{shipment.tracking_number}</a> : shipment.tracking_number}</p>}</article>; })}</section></main>;
}
